environment: production

logging:
  file:
    name: logs/se452RR-prod.log
  pattern:
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    root: WARN
    org.springframework: ERROR
    edu.depaul.cdm.se452: INFO

spring:
  jpa:
    generate-ddl: true
    show-sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:se452RRprod
  server:
    ssl:
      key-store: classpath:se452key.jks
      key-store-type: pkcs12
      key-store-password: testpwd
      key-alias: se452key
    port: 8443
  security:
    user: 
      name: testuser
      password: testpwd


  